<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<title>Higher Learning Marketers - Website Terms And Conditions</title>
<link rel="shortcut icon" href="<?php echo Yii::app()->theme->baseUrl;?>/img/icons/favicon.ico">
<link href="<?php echo Yii::app()->baseUrl; ?>/themes/neon/adcopy/style-blue.css" rel="stylesheet">
<script type="text/javascript">
(function(document, window){
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "https://api.pushnami.com/scripts/v1/pushnami-adv/5da7456e7e1a360012f6040d";
    script.onload = function() {
        Pushnami
            .update()
            .prompt()
    };
    document.getElementsByTagName("head")[0].appendChild(script);
})(document, window);
</script>
<script type="text/javascript" src="manifest.json"></script>
<script type="text/javascript" src="service-worker.js"></script>
</head>

<body>
<div id="sitagreement" class="page-container">
<div class="MsoNormal">
<a class="image" target="_blank" href="http://www.higherlearningapp.com">
<img src="<?php echo Yii::app()->baseUrl; ?>/images/privacy.jpg" border="0" width="728" height="90"></a></div>

<p>HigherLearningMarketers - Website Terms And Conditions</p>

<h6>Last Updated: 9/1/2016</h6>

<p>Thank you for visiting the HigherLearningMarketers and HigherLearningApp websites located at www.HigherLearningApp.com (the “Site”). The Site is an Internet property of HigherLearningMarketers.com. (“HigherLearningApp”, “we”  or “us”). By using and/or accessing the Site, you are agreeing to comply with and be bound by the following HigherLearningMarketers Website Terms and Conditions (“Terms and Conditions”). These Terms and Conditions are inclusive of any operating rules, policies, price schedules or other supplemental terms and conditions or documents expressly incorporated herein by reference and/or published from time to time including, without limitation, the separate HigherLearningApp Affiliate Agreement, HigherLearningMarketer's Advertiser Agreement and HigherLearningMarketers Privacy Policy (collectively, the “Network Agreements” and, together with these Terms and Conditions, the “Agreement”). Where there is a conflict between these Terms and Conditions and any Network Agreement, the applicable Network Agreement shall take precedence on all matters. Please review the terms of the Agreement carefully. If you do not agree to the Agreement in its entirety, you are not authorized to use the Site in any manner or form.
Registration</p>
<p>
The Site is available only to individuals who can enter into legally binding contracts under applicable law. To begin the enrollment process, you must submit a complete and accurate Affiliate application (“Application”). To join the Network, you must be an entity or an individual of at least eighteen (18) years of age, with the requisite equipment and Internet connection to access the Network and Site. The Site is not intended for use by individuals under the age of eighteen (18). If you are under the age of eighteen (18), you do not have permission to use and/or access the Site. HigherLearningMarketers will evaluate your Application and promptly notify you of your Application acceptance or rejection via the email address that you supply as a part of your Application. If any of the information supplied as part of your Application changes, at any time, you must immediately inform HigherLearningMarketers of same to reflect such changes in your Affiliate profile.</p>

<h6>Acceptance of Agreement</h6>
<p>You agree to the terms and conditions outlined in the Agreement with respect to your use of the Site. The Agreement constitutes the entire and only agreement between you and HigherLearningMarketers with respect to your use of the Site, and supersedes all prior or contemporaneous agreements, representations, warranties and/or understandings with respect to the Site. We may amend the Agreement from time to time in our sole discretion, without specific notice to you. Any such modifications shall take effect immediately. The latest Agreement will be posted on the Site, and you should review the Agreement prior to using the Site. By your continued use of the Site, you hereby agree to comply with all of the terms and conditions contained within the Agreement effective at that time. Therefore, you should regularly check this page for updates and/or changes. If you do not agree to any such modified terms, do not use this Site in any manner or form.</p>
<p>HigherLearningMarketers Network - HigherLearningMarketers.com,
HigherLearningApp.com, HigherLearningApplication.com and
HigherLearnerMarketers.com</p>

<p>Only by registering on the Site, completing the applicable HigherLearningMarketers Network Agreement as either an Affiliate or Advertiser and receiving approval from HigherLearningMarketers, can you utilize the affiliate marketing network operated by HigherLearningMarketers (the “HigherLearningMarketers Network”). The HigherLearningMarketers Network allows: (a) interested third party Affiliates including, but not limited to, marketers, publishers, advertisers and advertising agencies, to obtain Creative Materials (as that term is defined in the applicable Network Agreement) for various Advertiser products and/or services and market such products and/or services on Affiliate websites and/or through other online media as authorized by HigherLearningMarketers; and (b) interested Advertisers to attract and retain third party Affiliates in connection with the marketing of their products and/or services. HigherLearningMarketers reserves the right to prohibit any conduct by Advertisers and Affiliates. Notwithstanding the foregoing, HigherLearningMarketers undertakes no responsibility to monitor or otherwise police the use of Creative Materials or other activities of Affiliates, Advertisers and/or other third parties. You understand and agree that HigherLearningMarketers will not be responsible for such Creative Materials and other information. You agree that HigherLearningMarketers shall have no obligations and incur no liabilities to you in connection with any Creative Materials and other information appearing in the HigherLearningMarketers Network or otherwise made available by and through the Site.
</p>

<p>Please use caution, common sense and safety when using the HigherLearningMarketers Network and/or other areas of the Site. You are solely responsible for your interactions with other Site-users including, but not limited to, Affiliates, Advertisers and/or other third parties. Because we are not involved in such interactions, in the event that you have a dispute with one or more Site-users, Affiliates, Advertisers and/or other third parties, you hereby release HigherLearningMarketers including, but not limited to, its officers, directors, members, agents, subsidiaries and employees, from any and all claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of, or in any way connected with, such disputes. HigherLearningMarketers reserves the right, but has no obligation, to monitor disputes between you and other Site-users, Affiliates, Advertisers and/or other third parties.</p>

<p>
Unless explicitly stated otherwise, any future offer(s) made available to you on the Site that augment(s) or otherwise enhance(s) the current features of the Site shall be subject to the Agreement. You understand and agree that HigherLearningMarketers is not responsible or liable in any manner whatsoever for your inability to use and/or qualify as either an Affiliate or Advertiser for any current or intended marketing campaign or any associated functionality. You understand and agree that HigherLearningMarketers shall not be liable to you or any third party for any modification, suspension or discontinuation of the HigherLearningMarketers Network, any HigherLearningMarketers products and/or services or any products and/or services by any of the Affiliates and/or Advertisers. These Terms and Conditions only govern your use of the Site and ability to register for the services provided on the Site. To access the HigherLearningMarketers Affiliate Agreement, Click Here. To access the HigherLearningMarketers Privacy Policy (“Privacy Policy”), Click Here.</p>

<h6>License Grant</h6>
<p>
As a user of the Site, you are granted a non-exclusive, non-transferable, revocable and limited license to access and use the Site and associated content in accordance with the Agreement. As an Affiliate or Advertiser, you shall be subject to the restrictions contained in the applicable Network Agreement regarding use of the Creative Materials, the HigherLearningMarketers Network and other materials made available therein. HigherLearningMarketers may terminate this license at any time for any reason. You may use the Site on one computer for your own personal, non-commercial use. No part of the Site may be reproduced in any form or incorporated into any information retrieval system, electronic or mechanical. You may not use, copy, emulate, clone, rent, lease, sell, modify, decompile, disassemble, reverse engineer or transfer the Creative Materials, Site, any content featured therein or any portion thereof. HigherLearningMarketersreserves any rights not explicitly granted in the Agreement. You may not use any device, software or routine to interfere or attempt to interfere with the proper working of the Site or HigherLearningMarketers Network. You may not take any action that imposes an unreasonable or disproportionately large load on HigherLearningMarketers infrastructure. Your right to use the Site is not transferable.</p>

<h6>Proprietary Rights</h6>

<p>The Creative Materials, content, organization, graphics, design, compilation, magnetic translation, digital conversion, software, services and other matters related to the Site and HigherLearningMarketers Network are protected under applicable copyrights, trademarks and other proprietary (including, but not limited to, intellectual property) rights. The copying, redistribution, publication or sale by you of any part of the Creative Materials, HigherLearningMarketers Network or Site is strictly prohibited. You do not acquire ownership rights in or to any Creative Materials, content, document, software, services or other materials viewed at or through the Site and HigherLearningMarketers Network. The posting of information or material on the Site and HigherLearningMarketers Network by HigherLearningMarketers does not constitute a waiver of any right in such information and/or materials. Your use of this Site and HigherLearningMarketers’ services does not confer any intellectual property rights to you in the content you access or the services you use.</p>

<h6>Editing, Deleting and Modification</h6>
<p>We reserve the right in our sole discretion to edit and/or delete any documents, information or other content appearing on the Site.</p>
<h6>Indemnification</h6>
<p>You agree to indemnify and hold HigherLearningMarketers, its parents, subsidiaries and affiliates, and each of their respective members, officers, directors, employees, agents, co-branders and/or other partners, harmless from and against any and all claims, expenses (including reasonable attorneys’ fees), damages, suits, costs, demands and/or judgments whatsoever, made by any third party due to or arising out of: (a) your use of the Site, Creative Materials and/or HigherLearningMarketers Network; (b) your breach of the Agreement; and/or (c) any dispute between you and any Site-User, Affiliate, Advertiser, any third party or other entity. The provisions of this paragraph are for the benefit of HigherLearningMarketers, its parents, subsidiaries and/or affiliates, and each of their respective officers, directors, members, employees, agents, shareholders, licensors, suppliers and/or attorneys. Each of these individuals and entities shall have the right to assert and enforce these provisions directly against you on its own behalf.</p>

<h6>Disclaimer of Warranties</h6>
<p>THE SITE, THE HigherLearningMarketers NETWORK, CREATIVE MATERIALS AND/OR ANY PRODUCTS AND/OR SERVICES THAT YOU MAY APPLY FOR THROUGH THE SITE ARE PROVIDED TO YOU ON AN “AS IS” AND “AS AVAILABLE”  BASIS AND ALL WARRANTIES, EXPRESS AND IMPLIED, ARE DISCLAIMED TO THE FULLEST EXTENT PERMISSIBLE PUSUANT TO APPLICABLE LAW (INCLUDING, BUT NOT LIMITED TO, THE DISCLAIMER OF ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OF INTELLECTUAL PROPERTY AND/OR FITNESS FOR A PARTICULAR PURPOSE). IN PARTICULAR, BUT NOT AS A LIMITATION THEREOF, HigherLearningMarketers MAKES NO WARRANTY THAT: (A) THE SITE, THE HigherLearningMarketers NETWORK, CREATIVE MATERIALS AND/OR ANY PRODUCTS AND/OR SERVICES THAT YOU MAY APPLY FOR THROUGH THE SITE WILL MEET YOUR REQUIREMENTS; (B) THE SITE, THE HigherLearningMarketers NETWORK, CREATIVE MATERIALS AND/OR ANY PRODUCTS AND/OR SERVICES THAT YOU MAY APPLY FOR THROUGH THE SITE WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE; (C) YOU WILL QUALIFY AS EITHER AN AFFILIATE OR ADVERTISER; OR (D) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SITE AND/OR HigherLearningMarketers NETWORK WILL BE ACCURATE OR RELIABLE. THE SITE MAY CONTAIN BUGS, ERRORS, PROBLEMS OR OTHER LIMITATIONS. WE WILL NOT BE LIABLE FOR THE AVAILABILITY OF THE UNDERLYING INTERNET CONNECTION ASSOCIATED WITH THE SITE AND/OR HigherLearningMarketers NETWORK. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM HigherLearningMarketers OR OTHERWISE THROUGH OR FROM THE SITE, HigherLearningMarketers NETWORK, ANY AFFILIATE AND/OR ANY ADVERTISER, SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE AGREEMENT.</p>\

<h6>Limitation of Liability</h6>
<p>
YOU EXPRESSLY UNDERSTAND AND AGREE THAT HigherLearningMarketers SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL AND/OR EXEMPLARY DAMAGES INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF HigherLearningMarketers HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), TO THE FULLEST EXTENT PERMISSIBLE BY LAW FOR: (A) THE USE OR THE INABILITY TO USE THE SITE, THE HigherLearningMarketers NETWORK, CREATIVE MATERIALS AND/OR ANY PRODUCTS AND/OR SERVICES THAT YOU MAY APPLY FOR THROUGH THE SITE; (B) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION AND/OR SERVICES PURCHASED OR OBTAINED FROM, OR TRANSACTIONS ENTERED INTO THROUGH, THE SITE AND/OR HigherLearningMarketers NETWORK; (C) THE FAILURE TO QUALIFY AS EITHER AN AFFILIATE OR ADVERTISER; AND (D) ANY OTHER MATTER RELATING TO THE SITE, HigherLearningMarketers NETWORK, CREATIVE MATERIALS AND/OR ANY PRODUCTS AND/OR SERVICES THAT YOU MAY APPLY FOR THROUGH THE SITE. THIS LIMITATION APPLIES TO ALL CAUSES OF ACTION, IN THE AGGREGATE INCLUDING, BUT NOT LIMITED TO, BREACH OF CONTRACT, BREACH OF WARRANTY, NEGLIGENCE, STRICT LIABILITY, MISREPRESENTATIONS AND ANY AND ALL OTHER TORTS. YOU HEREBY RELEASE HigherLearningMarketers FROM ANY AND ALL OBLIGATIONS, LIABILITIES AND CLAIMS IN EXCESS OF THE LIMITATION STATED HEREIN. IF APPLICABLE LAW DOES NOT PERMIT SUCH LIMITATION, THE MAXIMUM LIABILITY OF HigherLearningMarketers™ TO YOU UNDER ANY AND ALL CIRCUMSTANCES WILL BE FIVE HUNDRED DOLLARS ($500.00). THE NEGATION OF DAMAGES SET FORTH ABOVE IS A FUNDAMENTAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN YOU AND HigherLearningMarketers™. THE SITE, THE HigherLearningMarketers NETWORK, CREATIVE MATERIALS AND/OR ANY PRODUCTS AND/OR SERVICES THAT YOU MAY APPLY FOR THROUGH THE SITE WOULD NOT BE PROVIDED TO YOU WITHOUT SUCH LIMITATIONS.</p>
<h6>Export Control</h6>

<p>Any Creative Materials made available from or through the Site are or may be subject to United States export controls. No such Creative Materials from the Site may be downloaded or otherwise exported or re-exported: (a) into (or to a national or resident of) Cuba, Iran, Iraq, Libya, Sudan, Syria, North Korea or any other country to which the United States has embargoed goods; or (b) to anyone on the U.S. Treasury Department’s list of Specially Designated Nationals or the U.S. Commerce Department’s Table of Denial Orders (each, a “Restricted List”). By using or downloading any Creative Materials from the Site, you are warranting that you are not located in, under the control of, or a national or resident of, any such country or on any Restricted List.</p>
<h6>Third Party Websites</h6>

<p>The Site may provide and/or refer you to links to other Internet websites and/or resources. The inclusion of a third party link to an outside website or resource on this Site should not be viewed as an endorsement of or recommendation for the third party website, the resource, or anything contained therein. Because HigherLearningMarketers has no control over the information, software, content, or creative material made available on such third party websites and/or resources, you hereby acknowledge and agree that HigherLearningMarketers is not responsible for the availability of such third party websites and/or resources, or for any damages and/or losses arising therefrom. Any access to and/or use of such third party websites and/or resources are done at your own risk.  Your dealings with third parties found on our through this Site, including payment and delivery of related products or services, and any associated terms, conditions, warranties, or representations, are solely between you and such third party.</p>

<h6>Privacy Policy</h6>

<p>Use of the Site, and all comments, feedback, information or materials that you submit through or in association with the Site, are subject to our Privacy Policy. We reserve the right to use all information regarding your use of the Site, and any and all other personally identifiable information provided by you, in accordance with the terms of our Privacy Policy. To view our Privacy Policy, Click Here.</p>

<h6>Legal Warning</h6>
<p>Any attempt by any individual, whether or not a HigherLearningMarketers customer, to damage, destroy, tamper with, vandalize and/or otherwise interfere with the operation of the Site, is a violation of criminal and civil law and HigherLearningMarketers will diligently pursue any and all remedies in this regard against any offending individual or entity to the fullest extent permissible by law and in equity.</p>

<h6>Disputes; Choice of Law; Venue</h6>
<p>The Agreement shall be treated as though it were executed and performed in the State of
New York and shall be governed by and construed in accordance with the laws of the State of
New York (without regard to conflict of law principles). Should a dispute arise concerning the terms and conditions of the Agreement, or the breach of same by any party hereto, the parties agree to submit their dispute for resolution by arbitration before the American Arbitration Association in
NY, New York, in accordance with the then current Commercial Arbitration rules of the American Arbitration Association. Any award rendered shall be final and conclusive to the parties and a judgment thereon may be entered in any court of competent jurisdiction. Nothing herein shall be construed to preclude any party from seeking injunctive relief in order to protect its rights pending arbitration. To the extent permitted by law, you agree that you will not bring, join or participate in any class action lawsuit as to any claim, dispute or controversy that you may have against HigherLearningMarketers and its employees, officers, directors, members, representatives and assigns. You agree to the entry of injunctive relief to stop such a lawsuit or to remove you as a participant in the suit. You agree to pay the attorney's fees and court costs that HigherLearningMarketers incurs in seeking such relief. The Agreement does not constitute a waiver of any of your rights and remedies to pursue a claim individually and not as a class action in binding arbitration as provided above. This provision preventing you from bringing, joining or participating in class action lawsuits is an independent agreement. Should any part of the Agreement be held invalid or unenforceable, that portion shall be construed consistent with applicable law and the remaining portions shall remain in full force and effect.</p>

<h6>Entire Agreement</h6>
<p>The Agreement is personal between you and HigherLearningMarketers and governs your use of the Site, superseding any and all prior and/or contemporaneous agreements between you and HigherLearningMarketers. To the extent that anything in or associated with the Site and/or any HigherLearningMarketers offering is in conflict or inconsistent with the Agreement, the Agreement shall take precedence; provided, however, that where there is a conflict between the Agreement and the Services Agreement, the Services Agreement shall take precedence on all matters; provided, however, that where there is a conflict between the Agreement and any Network Agreement, the applicable Network Agreement shall take precedence on all matters. Our failure to enforce any provision of the Agreement shall not be deemed a waiver of such provision nor of the right to enforce such provision. The parties do not intend that any agency or partnership relationship be created through operation of the Agreement.</p>

<h6>Contact Higher Learning Marketers</h6>
<p>
If you have any questions regarding the Agreement, or would like more information from us, please contact us at:
<a href="mailto:support@higherlearningmarketers.com">support@HigherLearningMarketers.com</a>.</p>
<p>HigherLearningMarketers.com</p>
<p>105-10 62nd Road, Suite 1D</p>
<p>Forest Hills, NY 11375</p>
<p>Phone Number:</p>
<p>1-718-699-1904</p>
<p>Fax Number:</p>
<p>1-212-202 -6367</p>
</body>

</html>